### ISSUE TITLE
Broken UI elements, unnecessary links

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/snitch#12]
Missing filter bar/search/pagination if no search results:
![bildschirmfoto 2016-11-29 um 14 08 43](https://cloud.githubusercontent.com/assets/870475/20716607/1c636a9c-b653-11e6-955a-0bce464201e6.png)

If results are there everything is fine:
![bildschirmfoto 2016-11-29 um 14 08 58](https://cloud.githubusercontent.com/assets/870475/20716608/1c88b720-b653-11e6-9daf-97422f08bfb6.png)

Quickedit is possible but makes no sense:
![bildschirmfoto 2016-11-29 um 14 09 34](https://cloud.githubusercontent.com/assets/870475/20716609/1c8c6794-b653-11e6-95ce-e01e8133ca5d.png)

Edit is possible but makes no sense: 
![bildschirmfoto 2016-11-29 um 14 09 58](https://cloud.githubusercontent.com/assets/870475/20716612/1c96036c-b653-11e6-8251-364b22edb153.png)

These links should be removed completely:
![bildschirmfoto 2016-11-29 um 14 10 16](https://cloud.githubusercontent.com/assets/870475/20716610/1c9471fa-b653-11e6-9509-ca6c0cf059b6.png)

What is happening to some of those buttons? These are nested `code` tags. Feature or bug?
![bildschirmfoto 2016-11-29 um 14 11 48](https://cloud.githubusercontent.com/assets/870475/20716611/1c956f56-b653-11e6-9906-420044cafa8e.png)

**Comment by staude** [comment]
@Zodiac1978 

>Missing filter bar/search/pagination if no search results:

its a wordpress default, look this screen 

![2017-03-02_1104](https://cloud.githubusercontent.com/assets/870951/23502423/2295ed08-ff38-11e6-9bba-7e68ee9acc34.png)

>These links should be removed completely

PR is coming
