### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by staude** [pluginkollektiv/snitch#19]
Warning: Illegal string offset 'type' in /www/htdocs/w0144eee/staude.net/wp-content/plugins/snitch/inc/snitch_cpt.class.php on line 565

Warning: Illegal string offset 'name' in /www/htdocs/w0144eee/staude.net/wp-content/plugins/snitch/inc/snitch_cpt.class.php on line 566

<img width="1529" alt="2017-07-15_1700" src="https://user-images.githubusercontent.com/870951/28240276-302024f0-697f-11e7-844b-257978f3f991.png">

**Comment by chesio** [comment]
It seems that this has been fixed already in d59d3cac967025e65b976dbb143ebb7961df8255 (see #4).
