### ISSUE TITLE
Snitch reporting connections for non-existing files

### ISSUE THREAD

**Issue by atomGit** [pluginkollektiv/snitch#32]
wp 5.3.2
snitch 1.1.8

Snitch reports connections for files that don't exist, all of which are .json files - for example...

`https://downloads.wordpress.org/plugin-checksums/goodbye-captcha/.json`

**Comment by atomGit** [comment]
whoops - i noticed a commonality here that might indicate that Snitch is not to blame - all of these erroneous file names originate from the same plugin...

`Plugin: WP Fingerprint
/wp-content/plugins/wp-fingerprint/inc/class-wpfingerprint-transport-wporg.php:37`

**Comment by staude** [comment]
Thanks for your feedback. 

Snitch reports all connections going outside, regardless of what is returned as status. Even if the response from the server is 404, the data was sent to the server and possibly received anyway. 

But it would be a conceivable extension to distinguish the connection status by color.

So I will close this ticket and set a feature request for the color.
